x-common: &common
  build:
    context: ..
    dockerfile: docker/Dockerfile
  depends_on:
    - postgres-qa-service
  env_file:
    - ../app/.env
  environment:
  - PYTHONPATH=/app/app
  volumes:
    - ../app:/app/app
  working_dir: /app

services:
  postgres-qa-service:
    image: postgres:14
    restart: always
    env_file:
    - ../app/.env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "25432:5432"

  app-qa-service:
    <<: *common
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "postgres-qa-service:5432", "--", "uvicorn", "app.main:application", "--host", "0.0.0.0", "--port", "8000"]

  alembic-qa-service:
    <<: *common
    entrypoint: ["./wait-for-it.sh", "postgres-qa-service:5432", "--"]
    command: ["sh", "-c", "cd app && alembic -c alembic.ini upgrade head"]

volumes:
  pgdata: